import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import React from "react";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` ${robotoMono.variable}`}>{children}</body>
    </html>
  );
}
